- de/admin/parameters.md
- en/admin/parameters.md
- fr/admin/parameters.md
- it/admin/parameters.md
The `database_charset` was missing in the default `parameters.yml` file
> Add missing database_charset in parameters page

- en/admin/installation/virtualhosts.md
- fr/admin/installation/virtualhosts.md
Fixed the Require instruction for Apache 2.4, a typo was preventing it from reloading successfully.
> Fixed typo for Apache 2.4 in virtual hosts install instructions

- en/user/errors_during_fetching.md
- fr/user/errors_during_fetching.md
I though it would be a good addition to describe how to enable log for debugging a fetching error.
Following https://github.com/wallabag/wallabag/issues/3261
> Add a step by step to log fetching error

- de/user/errors_during_fetching.md
- en/user/errors_during_fetching.md
- fr/user/errors_during_fetching.md
- it/user/errors_during_fetching.md
graby should now [log an error message](https://github.com/j0k3r/graby/pull/114) when the request fail. When it does that, the whole logs related to the request will be written in the production log. It might help debugging the problem.
Also, I moved some part of the error documentation so user will have to check for error message in production log, then enable dev log and finally try to fix the problem by writing a siteconfig.
What do you think about that?
> Add a part to check for production log

- en/developer/docker.md
i wanted to add a note for docker usage since we have two docker configs. offical one and the one in wallabag repo being used in development.
If it is okay for you to add this note, we can also translate it
PS: i created this commit at my fork of this repo since i am not allowed to create a branch at this repo anymore. this worked in past for me.
> add a note on when to use which docker config

- en/README.md
- en/admin/installation/installation.md
- en/admin/installation/requirements.md
- en/admin/parameters.md
- en/admin/query-upgrade-22-23.md
- en/admin/upgrade.md
Tada. 
I tried SQLite, MySQL and Postgresql upgrades, from 2.2.3 to 2.3.0. All is fine. 
All the queries are OK. 
We need :fr:, :de: and :it: too, but I think that we should merge this first PR for our users. 
Fix https://github.com/wallabag/wallabag/issues/3493
> Updated documentation for 2.3 install / upgrade

- de/user/import/README.md
- en/user/import/README.md
- fr/user/import/README.md
- it/user/import/README.md
This commit adds a link to the pinboard import documentation to the
root import readme for each language. It also makes the order
consistent across languages.
> add pinboard to root import readme table of contents

- en/admin/parameters.md
- fr/admin/parameters.md
Because migrations won’t work on MySQL & SQLite.
Following https://github.com/wallabag/wallabag/pull/3538
> Avoid hyphen in prefix

- en/admin/installation/virtualhosts.md
- fr/admin/installation/virtualhosts.md
I have added a description about how to correctly pass Authorization header to PHP-FPM in Apache (s. wallabag/wallabag#2768.
So far only in English...
> hint about Authorization header when using Apache with PHP-FPM

- en/admin/installation/virtualhosts.md
- fr/admin/installation/virtualhosts.md
Small update for the Virtualhosts pages, in French and English.
1. "Factorization" of the location of installation at the top;
2. Warning about installing in subfolders instead of the root of a domain, to avoid too much tickets.
> Warning about virtualhosts

- book.json
- de/admin/installation/requirements.md
- de/admin/parameters.md
- en/admin/installation/installation.md
- en/admin/installation/requirements.md
- en/admin/installation/virtualhosts.md
- en/admin/parameters.md
- en/developer/paywall.md
- en/user/articles/restricted.md
- fr/admin/installation/requirements.md
- fr/admin/installation/virtualhosts.md
- fr/admin/parameters.md
- fr/developer/paywall.md
- fr/user/articles/restricted.md
- it/admin/installation/requirements.md
- it/admin/parameters.md
- it/developer/paywall.md
The plugin alerts shows issues with following blocks.
Using hints instead, even if also not updated, allows for a cleaner result.
> Use of hints plugin instead of alerts

- en/user/errors_during_fetching.md
- fr/user/errors_during_fetching.md
I updated the FR & EN documentation, following the merge of a "full debug mode" for graby.
Fix https://github.com/wallabag/wallabag/issues/3801
Merge only if the weird behavior of wallabag regarding graby's logs configuration is acceptable.
> Graby debug(s) mode activation

- en/admin/installation/rightaccess.md
Even if it should already associated to the right group / user.
Fix https://github.com/wallabag/wallabag/issues/2373
> Add missing `web` folder

- en/SUMMARY.md
- en/admin/upgrade.md
Without linking to it, the page isn't generated and just copy/pasted as a md file.
> Fix query upgrade 22-23 generation

- en/admin/query-upgrade-21-22.md
- en/admin/query-upgrade-22-23.md
- en/admin/upgrade.md
Add a short description to queries upgrade.
Add a tip about having `composer` installed before running the upgrade.
Add a tip when getting an error related to a git repository (which means installation was done using a package and not git)
Define some numeric list for shared hosting upgrade (more readable)
See https://github.com/wallabag/wallabag/issues/4007
> Update the upgrade part

- en/admin/asynchronous.md
Looks like it doesn't work anymore on 2.4 when using `-e=prod`:
>   The file "/Users/j0k/Sites/github/wallabag/app/config/config_=prod.yml" does not exist.
> Fix environment for async command

- de/admin/installation/requirements.md
- en/admin/installation/requirements.md
- fr/admin/installation/requirements.md
- it/admin/installation/requirements.md
When running `make dev` to hack on Wallabag, some dependency fails because I didn’t have `php-intl` so I added a `PHP extensions for development` on the page of requirements.
Only added on `en` and `fr` languages, sorry.
> 📝 Add development required PHP extensions section

- en/admin/installation/virtualhosts.md
Only adding RewriteRule makes apache return a Forbidden error with
the following message in the logs:
> Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions
This change avoids that issue.
> Fix apache error on mod_rewrite section

- de/admin/console_commands.md
- en/admin/console_commands.md
- fr/admin/console_commands.md
- it/admin/console_commands.md
But also add missing commands: `wallabag:generate-hashed-urls`
And ensure `--env=prod` is used to be consistent with the rest of the doc.
Following https://github.com/wallabag/wallabag/pull/4844
> Add `wallabag:clean-downloaded-images` commands

- en/admin/parameters.md
- fr/admin/parameters.md
`server_name` is expected to land in wallabag 2.4.1, see https://github.com/wallabag/wallabag/pull/4301
> Add new parameter: server_name

- en/admin/installation/installation.md
The wallabag app id was changed for migration to the latest version.
> Update cloudron app id

- en/admin/installation/virtualhosts.md
Solution provided by @rEnr3n  in #130.  
Tested in amd64 gentoo using caddy 2.3.0.  Seems to be working perfectly.
> Added working caddy 2 configuration to virtualhost instructions

- en/user/errors_during_fetching.md
Added documentation to make how stripping elements with site configs works as stated here: https://github.com/j0k3r/graby/issues/288
> Add note on non-standard HTML elements

- de/user/configuration/tagging_rules.md
- en/user/configuration/tagging_rules.md
- fr/user/configuration/tagging_rules.md
- it/user/configuration/tagging_rules.md
Use domain with subdomain `www.php.net` instead of `github.com` as `domainName` example in tagging rules docs. This should make it more clear that the subdomain is required for equality.
Fixes wallabag/doc#104
This change affects all translations in documentation and wallabag source.
Corresponding change in wallabag messages: wallabag/wallabag#5744
> Use site with subdomain as tagging rule example

- en/admin/query-upgrade-25-26.md
There is a typo left in the documentation for a postgres database. . In PostgreSQL, the INT data type does not have a length specifier like in some other database systems (e.g., MySQL).
> Correction of v25-26 upgrade typo

- en/admin/parameters.md
Wallabag [2.6.1](https://github.com/wallabag/wallabag/releases/tag/2.6.1) introduced a new `mailer_dsn` parameter (and removed all existing `mailer_*` parameters). This is a suggestion to add the related documentation.
Few comments/qeustions:
* I kept the old parameters since I'm not sure how you want to proceed here. Keep them documented or remove them?
* The [Symfony documentation](https://symfony.com/doc/4.4/mailer.html#using-built-in-transports) specifies that some parts of the string should be urlencoded. Hence the note.
* I kept the description short. Should it be made longer with all details from the old parameters?
> Document new "mailer_dsn" parameter

- en/user/articles/annotations.md
Annotation is not visible when revisiting the original page on the internet. Only when visiting the wallabag saved version.
> Clarify that annotation is not visible on the internet

- en/admin/common_errors.md
- en/admin/installation/installation.md
- en/admin/internal_settings.md
- en/apps/android.md
- en/user/articles/README.md
- en/user/articles/save.md
- en/user/configuration/settings.md
- en/user/create_account.md
- en/user/errors_during_fetching.md
- en/user/import/Readability.md
- en/user/tags.md
- fr/developer/api/resources.md
I noted a few typos and so went ahead and fixed them while also running codespell to detect a few more.
Would the maintainers of this repo be open to reviewing a PR that would try to improve phrasing across (not reorganizing anything) the docs here to be a bit clearer and grammatically correct?
> fix typos throughout the English docs

- content/admin/asynchronous.md
- content/admin/backup.md
- content/admin/common_errors.md
- content/admin/console_commands.md
- content/admin/custom_css.md
- content/admin/installation/requirements.md
- content/admin/installation/rightaccess.md
- content/admin/internal_settings.md
- content/admin/mailer.md
- content/admin/parameters.md
- content/admin/upgrade/_index.md
- content/apps/android.md
- content/apps/ios.md
- content/developer/api/methods.md
- content/developer/api/oauth.md
- content/developer/back-end.md
- content/developer/docker.md
- content/developer/front_end.md
- content/developer/paywall.md
- content/developer/testsuite.md
- content/developer/translate.md
Following up on https://github.com/wallabag/doc/pull/190#issuecomment-2455041670 went through the admin and development docs and tried to make them a bit clearer.
Please feel free to commit directly to this branch or comment with suggestions if you feel anything is off.
If this is satisfactory I'll give a pass at the documentation in the user folder too.
Trying to strike a balance between not changing too much in an opinionated way and making things as clear as possible :)
> Improve phrasing on admin and development docs

- content/admin/installation/installation.md
To avoid an error, indicate the needed double quote in the information about database_path for SQLite installations.
This crash:
```
database_path (null): %kernel.root_dir%/../data/db/wallabag.sqlite
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-cmd event terminated with an exception
In Inline.php line 310:
The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 67 (near "%kernel.root_dir%/../data/db/wallabag.sqlite").
```
This don't:
```
database_path (null): "%kernel.root_dir%/../data/db/wallabag.sqlite"
```
> wrap database_path for SQLite between quotes

- content/admin/installation/installation.md
This improves the docker command to launch the container. The `docker pull` command only fetches the container, but does not launch it. As such, it is not very useful.
With the updated invocation a Docker user can quickly spin up a ~Wallabag~wallabag instance for evaluation. For that reason, I chose port 8080 on the host machine since port 80 is often already taken. The `SYMFONY__ENV__DOMAIN_NAME` then reflects the host machine port number, otherwise CSS styles and other assets are broken in the browser. Additionally, wallabag data is persisted using Docker named volumes instead of mounting absolute paths on the host machine that may not exist.
I've removed the “Have a look at our repository” note because it does not link to anything and, if someone does look at the ~Wallabag~wallabag …
> More actionable Docker launch command in installation docs
