README.md
en/admin/console_commands.md
fr/admin/console_commands.md

Related: https://github.com/wallabag/wallabag/pull/2708

Update README & improve commands

---

de/developer/translate.md
en/developer/translate.md
fr/developer/translate.md
it/developer/translate.md

See https://github.com/wallabag/wallabag/pull/3177#issuecomment-305744154

wallabag_core has moved to wallabag.yml

---

README.md
en/admin/console_commands.md
fr/admin/console_commands.md

See https://github.com/wallabag/wallabag/pull/3179
Ping @wallabag/translators 🙂

Add information about wallabag:user:show

---

de/admin/parameters.md
en/admin/parameters.md
fr/admin/parameters.md
it/admin/parameters.md

See https://github.com/wallabag/wallabag/pull/3173

Add parameter domain_name

---

de/admin/parameters.md
en/admin/parameters.md
fr/admin/parameters.md
it/admin/parameters.md

Should fix https://github.com/wallabag/wallabag/issues/3086.
@matteocoder @jlnostr @Strubbl need your help again ;-)

Added notice about clearing cache for parameters.yml

---

de/admin/upgrade.md
de/developer/paywall.md
de/developer/translate.md
de/user/articles/save.md
de/user/import/README.md
de/user/import/wallabagv1.md
en/admin/upgrade.md
en/developer/paywall.md
en/developer/translate.md
en/user/articles/save.md
en/user/import/README.md
en/user/import/wallabagv1.md
fr/admin/upgrade.md
fr/developer/paywall.md
fr/developer/translate.md
fr/user/import/README.md
fr/user/import/wallabagv1.md
it/developer/translate.md

Fixed links with `/master/` in it.

Fix links with /master/

---

en/developer/api/oauth.md
fr/developer/api/oauth.md

Related https://github.com/wallabag/wallabag/pull/3227

Add grant_type method client_credentials

---

en/developer/api/oauth.md
fr/developer/api/oauth.md

Revert "Add grant_type method client_credentials"

---

en/admin/console_commands.md
fr/admin/console_commands.md

This is the doc going with https://github.com/wallabag/wallabag/pull/3326

Add documentation for the reload entry command

---

en/admin/console_commands.md
fr/admin/console_commands.md

This go with https://github.com/wallabag/wallabag/pull/3301.
I need help for the `de` translation.

Add documentation for the list users command

---

en/admin/installation/virtualhosts.md
fr/admin/installation/virtualhosts.md

English and french languages. See #35

Caddy server configuration

---

en/admin/parameters.md
fr/admin/parameters.md

See https://github.com/wallabag/wallabag/pull/3488

Add database_driver_class for PG 10

---

en/admin/installation/installation.md

Fix https://github.com/wallabag/wallabag/issues/3489

Added information about database_path for sqlite

---

de/developer/api/README.md
de/developer/api/methods.md
de/developer/api/oauth.md
en/developer/api/methods.md
en/developer/api/oauth.md
en/developer/api/readme.md
fr/developer/api.md
fr/developer/api/api.md
fr/developer/api/methods.md
fr/developer/api/oauth.md
fr/developer/api/readme.md
it/developer/api/methods.md
it/developer/api/oauth.md
it/developer/api/readme.md

Fix #18 
(I know that there are some duplicates in the french doc, we need to clean up but we'll merge #53 before).

Replaced localhost:8000 with app.wallabag.it

---

en/admin/installation/installation.md

Added documentation about Synology

---

en/user/articles/save.md

Small typo fix

---

en/SUMMARY.md
en/admin/common_errors.md
en/user/faq.md

Following https://github.com/wallabag/wallabag/issues/3036 & (the old) https://github.com/wallabag/wallabag/issues/2976

Add common errors

---

en/user/errors_during_fetching.md
fr/user/errors_during_fetching.md
it/user/errors_during_fetching.md

The logs are not in `var/log/prod.log` but in `var/logs/prod.log`

Set correct log file location

---

en/admin/installation/installation.md

Added a note for installation behind a squid as a reverse proxy

Added Reverse Proxy Notes

---

en/user/articles/restricted.md
fr/user/articles/restricted.md

Fix #85
I added most of the websites cited in https://github.com/wallabag/wallabag/issues/3439, even if I probably missed some of them.
Following discussions in #88, which was received somehow well (maybe?), I didn't bother updating German & Italian docs.

Update supported paywalled websites

---

en/README.md

Useful when accessing the doc via https://doc.wallabag.org

link to home page

---

en/admin/installation/installation.md
fr/admin/installation/installation.md

Also, quickly update the french doc
Fix https://github.com/wallabag/wallabag/issues/3578

Add a line about resetting the db when installing

---

en/README.md
en/admin/parameters.md
fr/README.md
fr/admin/parameters.md

Also update the mailer security part

Add sentry_dsn in parameters doc

---

en/admin/internal_settings.md
fr/admin/internal_settings.md

Also remove unecessary stuff & fix Diaspora escaping in FR

Add a tip about how to keep GIF animated

---

en/admin/installation/readme.md

Update readme.me to have proper link towards the installation process

Update readme.me to have proper link towards the installation process

---

en/admin/installation/readme.md
en/admin/installation/requirements.md
en/user/articles/save.md

Putting the domain force GitBook to open the link in a new tab.
Also, remove compat with PHP 5.6 as of wallabag 2.4

Fix some local urls

---

en/admin/installation/requirements.md

Add more information on how to fix it.
See https://github.com/wallabag/wallabag/issues/3961

Ensure user is using at least Composer 1.8

---

_redirects

Once the DNS propagation will be done and the HTTPS certificate will be regenerated, we'll have to merge that.

Add redirect from Netlify subdomain

---

en/admin/installation/requirements.md

php7-fpm is not listed anywhere as a requirement

added php7-fpm to requirements list

---

en/admin/parameters.md
fr/admin/parameters.md

See https://github.com/wallabag/wallabag/pull/4319

Add information about token lifetime configuration

---

en/SUMMARY.md
en/admin/custom_css.md
fr/SUMMARY.md
fr/admin/custom_css.md

See https://github.com/wallabag/wallabag/pull/4151 & https://github.com/wallabag/wallabag/pull/4272
Related https://github.com/wallabag/wallabag/projects/4#card-13774701

Add documentation about CSS customization

---

en/SUMMARY.md
en/admin/query-upgrade-23-24.md
en/admin/upgrade.md

I've run each migration from a 2.3.8 fresh install using SQLite, MySQL & PostgreSQL
Related https://github.com/wallabag/wallabag/projects/4#card-13774701

Add migration queries for 2.4

---

de/developer/front_end.md
en/developer/back-end.md
en/developer/front_end.md
fr/developer/back-end.md
fr/developer/front-end.md
it/developer/front_end.md

Also, fix how to run command using Yarn.
See https://github.com/wallabag/wallabag/pull/4627

Use Yarn to build assets

---

de/admin/asynchronous.md
de/admin/parameters.md
de/admin/upgrade.md
de/developer/front_end.md
de/user/configuration/user_information.md
en/admin/parameters.md
en/developer/front_end.md
en/user/configuration/user_information.md
fr/admin/asynchronous.md
fr/admin/parameters.md
fr/admin/upgrade.md
fr/developer/front-end.md
fr/user/configuration/user_information.md
it/admin/asynchronous.md
it/admin/parameters.md
it/admin/upgrade.md
it/developer/front_end.md
it/user/configuration/user_information.md

See https://github.com/wallabag/docker/issues/227

Fix `-e=prod` parameter

---

en/admin/query-upgrade-23-24.md

i was confused when reading the title ;-)

fixed title in upgrade doc

---

en/admin/installation/virtualhosts.md

Hi there,
Here is my proposal for an assets caching strategy.
Have a nice day and stay safe.

Apache assets caching strategy

---

en/user/errors_during_fetching.md
fr/user/errors_during_fetching.md

update reference link to the template

---

en/admin/installation/installation.md
fr/admin/installation/installation.md

Hi!
wallabag is available on our marketplace for a very easy installation.
Regards,

Add alwaysdata hosting on installation page

---

en/admin/internal_settings.md
en/user/articles/download.md
fr/admin/internal_settings.md
fr/user/articles/download.md

Related to https://github.com/wallabag/wallabag/issues/5773
Related to https://github.com/wallabag/wallabag/pull/5775

Add deprecation message for MOBI export

---

fr/user/articles/README.md

Hi, I was browsing the docs and noticed that this page was left untranslated in french, so I did a quick translation. Hope it helps.

Translation of articles/README.md in french

---

de/admin/internal_settings.md
de/user/articles/share.md
en/admin/internal_settings.md
en/user/articles/share.md
fr/admin/internal_settings.md
fr/user/articles/share.md
it/admin/internal_settings.md
it/user/articles/share.md

Now https://github.com/wallabag/wallabag/pull/6047 is merged, we can update documentation.

Removed unsupported share services

---

de/admin/installation/requirements.md
en/admin/installation/requirements.md
fr/admin/installation/requirements.md
it/admin/installation/requirements.md

Documentation about php version wasn't up-to-date.

Added consistency about php version

---

en/admin/query-upgrade-25-26.md
en/admin/upgrade.md

Add documentation about 2.6.x steps

---

en/admin/upgrade.md

Fix a typo in new parameter `mailer_dsn`

---

de/user/errors_during_fetching.md
en/user/errors_during_fetching.md

- added wallabagger section to errors_during_fetching.md English and German
- Feel free to change the text or move to a different position

Add wallabagger

---

en/admin/backup.md

The path hasn't changed :)
Fix https://github.com/wallabag/wallabag/issues/7493

Update backup about image
